server {
    listen 80;
    server_name localhost;

    # Define o diretório raiz para os arquivos do Flutter
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Tenta servir o arquivo solicitado diretamente.
        # Se não encontrar, redireciona para o index.html.
        # Isso é crucial para que o roteamento do Flutter (GoRouter) funcione.
        try_files $uri $uri/ /index.html;
    }

    # Configurações de cache para otimizar o carregamento
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}
