name: tech_wall
description: "TechWall."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  auto_size_text: ^3.0.0
  brasil_fields: ^1.18.0
  dio: ^5.8.0+1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_mdi_icons: ^0.1.3
  from_css_color: ^2.0.0
  go_router: ^16.2.1
  http: ^1.4.0
  intl: ^0.20.2
  linked_scroll_controller: ^0.2.0
  lucide_icons: ^0.257.0
  material_symbols_icons: ^4.2815.1
  multi_dropdown: ^3.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono/RobotoMono-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/RobotoMono/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
